urls = {
    'market-cap':
        'https://companiesmarketcap.com/page/',
    'most-profitable-companies':
        'https://companiesmarketcap.com/most-profitable-companies/page/',
    'largest-companies-by-revenue':
        'https://companiesmarketcap.com/largest-companies-by-revenue/page/',
    'top-companies-by-total-assets':
        'https://companiesmarketcap.com/top-companies-by-total-assets/page/',
    'top-companies-by-net-assets':
        'https://companiesmarketcap.com/top-companies-by-net-assets/page/',
    'companies-with-the-highest-liabilities':
        'https://companiesmarketcap.com/'
        'companies-with-the-highest-liabilities/page/',
    'companies-with-the-highest-debt':
        'https://companiesmarketcap.com/companies-with-the-highest-debt/page/',
    'companies-with-the-highest-cash-on-hand':
        'https://companiesmarketcap.com/'
        'companies-with-the-highest-cash-on-hand/page/',
}
